default:
  image: python:3.12-bookworm
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true
    - poetry install

stages:
  - lint

MyPy:
  stage: lint
  script:
    - mypy --config-file setup.cfg

Linter:
  stage: lint
  script:
    - flake8 --config-file setup.cfg
