apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc-pompeeva
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 100Mi
