apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8001"
  labels:
    {{- include "auth-service-pompeeva.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "auth-service-pompeeva.selectorLabels" . | nindent 4 }}
